apiVersion: v1
kind: Service
metadata:
  name: file-api-svc
  labels:
    app: file-api  # Includes both v1 and v2 versions of the App
spec:
  type: LoadBalancer
  ports:
  - port: 8888
    targetPort: 80
  selector:
    app: file-api